name: CI/CD for CarPricePredictor

on:
  push:
    branches:
      - main # trigger on push to main branch
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pandas numpy scikit-learn mlflow

      - name: Run tests
        run: |
          pytest test_model.py --maxfail=1 --disable-warnings -q

  deploy:
    name: Deploy if Tests Pass
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow

      - name: Deploy Model to MLflow
        env:
          MLFLOW_TRACKING_URI: https://mlflow.ml.brain.cs.ait.ac.th/
        run: |
          python scripts/deploy_model.py
